Question 1.Create a 1D NumPy array with numbers from 1 to 10.

In [4]:
import numpy as np

arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Question 2.Create a 3×3 matrix with all zeros.


In [5]:
import numpy as np

matrix = np.zeros((3,3))

print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Question 3.Create a 4×4 identity matrix.

In [7]:
import numpy as np 

matrix = np.eye((4))

print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 4.Print the 3rd element of an array.

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr[2])

3


Question 5.Print the last element of an array.

In [9]:
import numpy as np
arr = np.array([10,20,20,40])
print(arr[-1])

40


Question 6.Print elements from index 2 to 5.

In [10]:
import numpy as np

arr = [10,20,30,40,50,60,70]

print(arr[2:6])

[30, 40, 50, 60]


Question 7.Print alternate elements.

In [14]:
import numpy as np
 
arr = np.array([10,20,30,40,50,60,70])

print(arr[::2])

[10 30 50 70]


Question 8.Create a 4×4 matrix: x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]) 8.1 Print the 2nd row. 8.2 Print the 3rd column. 8.3 Print the submatrix: [[6,7], [10,11]]

In [12]:
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(x[1])
print(x[:2])
print(x[1:3,1:3])

[5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[ 6  7]
 [10 11]]


Question 9. Create an array from 1 to 12 and reshape it into: 9.1 3×4 matrix 9.2 2×6 matrix

In [18]:
import numpy as np

x = np.arange(1,13)

x.reshape(3,4)

x.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Question 10.Flatten any 3*3 matrix into a 1D array

In [24]:
import numpy as np

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(x.flatten())

[1 2 3 4 5 6 7 8 9]
